extensions:
  health_check:
   endpoint: "0.0.0.0:13133"
  pprof:
    endpoint: 0.0.0.0:1888
  zpages:
    endpoint: 0.0.0.0:55679
  basicauth/grafana_cloud:
    client_auth: 
      username: "910451"
      password: "glc_eyJvIjoiMTAyODc5MiIsIm4iOiJzdGFjay05MTA0NTEtb3RscC13cml0ZS1vdGxwIiwiayI6Imh0T1VDTXRNSjM0MngyRjA1UTFyajAyNyIsIm0iOnsiciI6InByb2QtdXMtd2VzdC0wIn19"  
  basicauth/otlp:
    client_auth:
      username: "868232"
      password: "glc_eyJvIjoiMTAyODc5MiIsIm4iOiJzdGFjay05MTA0NTEtaGwtcmVhZC1sb2tpLW90bHAiLCJrIjoiODgwa29TNHgxSzM0cDU2YXBuU1FpczNtIiwibSI6eyJyIjoicHJvZC11cy13ZXN0LTAifX0="
  basicauth/prometheus:
    client_auth:
      username: "1535416"
      password: "glc_eyJvIjoiMTAyODc5MiIsIm4iOiJzdGFjay05MTA0NTEtaG0td3JpdGUtcHJvbWV0aGV1cyIsImsiOiJSOHM1YmlySjRDMGFQdjE5NmN6MWo4WTYiLCJtIjp7InIiOiJwcm9kLXVzLXdlc3QtMCJ9fQ=="

connectors:
  grafanacloud:
    host_identifiers: ["host.name"]
    metrics_flush_interval: 60s    

receivers:
  otlp:
    protocols:
      http: 
       endpoint: 0.0.0.0:4318
  hostmetrics:
    collection_interval: 10s
    scrapers:
      paging:
        metrics:
          system.paging.utilization:
            enabled: true
      load:
        cpu_average: true
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true
      disk:
      filesystem:
        metrics:
          system.filesystem.utilization:
            enabled: true
      memory:
      network:
        metrics:
          system.network.connections:
            enabled: true
      process:

processors:
  batch:
    timeout: 10s
    send_batch_max_size: 1000
    send_batch_size: 100
  resourcedetection:
    detectors: [ecs, ec2, system, env]

exporters:
  # datadog:
  #   retry_on_failure:
  #     enabled: true
  #   api:
  #     site: 'datadoghq.com'
  #     key: 'eb7c2acc9758f779ac7a65eaecb9b8b5'
  otlphttp/grafana_cloud:
    endpoint: https://otlp-gateway-prod-us-west-0.grafana.net/otlp/v1/traces #https://chainsafe.grafana.net/loki/api/v1/push
    auth:
      authenticator: basicauth/grafana_cloud
    encoding: json

  prometheusremotewrite:
    endpoint: "https://prometheus-prod-36-prod-us-west-0.grafana.net/api/prom/push"
    auth:
      authenticator: basicauth/prometheus

  otlphttp/loki:
    endpoint: "https://logs-prod-021.grafana.net/loki/api/v1/push"
    auth:
      authenticator:  basicauth/otlp

service:
  extensions: [health_check, pprof, zpages, basicauth/grafana_cloud, basicauth/otlp, basicauth/prometheus]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/grafana_cloud]
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [resourcedetection, batch]
      exporters: [prometheusremotewrite]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/loki]
