
receivers:
  otlp:
    protocols:
      http:
        endpoint: localhost:4318

processors:
  batch:

***REMOVED***
***REMOVED***
***REMOVED***
REDACTED

  logging:

service:
  pipelines:
    traces:
      receivers:
      - otlp
      processors:
      - batch
      ***REMOVED***
      - logging
      - datadog
    metrics:
      receivers:
      - otlp
      processors:
      - batch
      ***REMOVED***
      - datadog
      - logging