extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317
      http:
        endpoint: localhost:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: 'sygma_relayers'
          static_configs:
            - targets: ['localhost:8888']

processors:
  batch:

***REMOVED***
***REMOVED***
***REMOVED***

  logging:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200
  otlp:
    endpoint: 'https://relayers.com:4318'
  otlphttp:
    endpoint: 'https://sygma-relayers.com:4318'
  prometheus:
    endpoint: http://localhost:8888/metrics
    namespace: default
    send_timestamps: true
    metric_expiration: 180m
    enable_open_metrics: true
    resource_to_telemetry_conversion:
      enabled: true
  prometheusremotewrite:
    endpoint: https://aps-workspaces.us-east-2.amazonaws.com/workspaces/ws-32bde15a-a908-4003-a30e-666f482168c7/api/v1/remote_write
    tls:
      insecure: true

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      ***REMOVED*** [datadog, otlp, otlphttp]
    metrics:
      receivers: [otlp, prometheus]
      processors:  [batch]
      ***REMOVED*** [datadog, logging, prometheus, otlp, otlphttp, prometheusremotewrite]
    logs:
      receivers: [otlp]
      processors: [batch]
      ***REMOVED*** [logging, datadog, otlp, otlphttp]