extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679
  basicauth/otlp:
    client_auth:
      username: 635704
REDACTED
receivers:
  otlp:
    protocols:
      grpc:
      http:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'sygma_relayers'
          static_configs:
            - targets: [localhost:8888, localhost:9000, localhost:9001]
          scheme: tcp     
  hostmetrics:
    collection_interval: 10s
    scrapers:
      paging:
        metrics:
          system.paging.utilization:
            enabled: true
      load:
        cpu_average: true
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true
      disk:
      filesystem:
        metrics:
          system.filesystem.utilization:
            enabled: true
      memory:
      network:
        metrics:
          system.network.connections:
            enabled: true
      process:

processors:
  batch:
    timeout: 10s
    send_batch_max_size: 1000
    send_batch_size: 100
  resourcedetection:
    detectors: [ecs, ec2, system]

***REMOVED***
***REMOVED***
    retry_on_failure:
      enabled: true
***REMOVED***
      site: 'datadoghq.com'

  logging:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200
  otlphttp:
    auth:
      authenticator: basicauth/otlp
    endpoint: https://otlp-gateway-prod-us-central-0.grafana.net/otlp
  prometheus:
    endpoint: 'localhost:8889'
    namespace: default
    send_timestamps: true
    metric_expiration: 180m
    enable_open_metrics: true
    resource_to_telemetry_conversion:
      enabled: true

service:
  extensions: [health_check, pprof, zpages, basicauth/otlp]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      ***REMOVED*** [datadog, logging, otlphttp]
    metrics:
      receivers: [otlp, prometheus, hostmetrics]
      processors:  [batch]
      ***REMOVED*** [datadog, logging, prometheus, otlphttp]
    logs:
      receivers: [otlp]
      processors: [batch]
      ***REMOVED*** [logging, datadog, otlphttp]