
receivers:
  otlp:
    protocols:
      http:
        endpoint: localhost:4318

processors:
  batch:

exporters:
  datadog:
    api:
      site: 'datadghq.com'
      key: 'eb7c2acc9758f779ac7a65eaecb9b8b5'
  logging:

service:
  pipelines:
    traces:
      receivers:
      - otlp
      processors:
      - batch
      exporters:
      - logging
      - datadog
    metrics:
      receivers:
      - otlp
      processors:
      - batch
      exporters:
      - datadog
      - logging