extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317
      http:
        endpoint: localhost:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: 'sygma_relayers'
          static_configs:
            - targets: ['0.0.0.0:9001', '0.0.0.0:9000']
          scheme: tcp     

processors:
  batch:

exporters:
  datadog:
    api:
      site: 'datadoghq.com'
      key: '${{ secrets.DD_SITE }}'
  logging:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200
  otlp:
    endpoint: '0.0.0.0:4317'
    tls:
      insecure: true
  otlphttp:
    endpoint: 'http://0.0.0.0:4318'
  prometheus:
    endpoint: 'localhost:8889'
    namespace: default
    send_timestamps: true
    metric_expiration: 180m
    enable_open_metrics: true
    resource_to_telemetry_conversion:
      enabled: true

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog, otlp, otlphttp, logging]
    metrics:
      receivers: [otlp, prometheus]
      processors:  [batch]
      exporters: [datadog, logging, prometheus, otlp, otlphttp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, datadog, otlp, otlphttp]