extensions:
  health_check:
   endpoint: "0.0.0.0:13133"
  pprof:
    endpoint: 0.0.0.0:1888
  zpages:
    endpoint: 0.0.0.0:55679
  basicauth/grafana_cloud:
    client_auth: 
      username: "${env:USER_ID}"
      password: "${env:GRAFANA_CLOUD}"  

connectors:
  grafanacloud:
    host_identifiers: ["host.name"]
    metrics_flush_interval: 60s    

receivers:
  otlp:
    protocols:
      http: 
       endpoint: 0.0.0.0:4318
  hostmetrics:
    collection_interval: 10s
    scrapers:
      paging:
        metrics:
          system.paging.utilization:
            enabled: true
      load:
        cpu_average: true
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true
      disk:
      filesystem:
        metrics:
          system.filesystem.utilization:
            enabled: true
      memory:
      network:
        metrics:
          system.network.connections:
            enabled: true
      process:

processors:
  batch:
    timeout: 10s
    send_batch_max_size: 1000
    send_batch_size: 100
  resourcedetection:
    detectors: [ecs, ec2, system, env]

***REMOVED***
  debug:
    verbosity: detailed
  otlphttp/grafana_cloud:
    endpoint: "${env:ENDPOINT}" 
    auth:
      authenticator: basicauth/grafana_cloud
    encoding: json

service:
  extensions: [health_check, pprof, zpages, basicauth/grafana_cloud]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      ***REMOVED*** [debug, otlphttp/grafana_cloud]
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [resourcedetection, batch]
      ***REMOVED*** [otlphttp/grafana_cloud]
    logs:
      receivers: [otlp]
      processors: [batch]
      ***REMOVED*** [otlphttp/grafana_cloud, debug]
