receivers:
  otlp:
    protocols:
      http:
        endpoint: localhost:4318
  # The hostmetrics receiver is required to get correct infrastructure metrics in Datadog.
  # hostmetrics:
  #   collection_interval: 10s
  #   scrapers:
  #     paging:
  #       metrics:
  #         system.paging.utilization:
  #           enabled: true
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true
      disk:
      filesystem:
        metrics:
          system.filesystem.utilization:
            enabled: true
      load:
      memory:
      network:
      processes:
  # The prometheus receiver scrapes metrics needed for the OpenTelemetry Collector Dashboard.
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otelcol'
        scrape_interval: 10s
        static_configs:
        - targets: ['0.0.0.0:8888']

  filelog:
    include_file_path: true
    poll_interval: 500ms
    include:
      - /var/log/**/*relayer*/*.log

processors:
  batch:
    send_batch_max_size: 100
    send_batch_size: 10
    timeout: 10s

***REMOVED***
***REMOVED***
***REMOVED***
REDACTED


service:
  pipelines:
    metrics:
      receivers: [hostmetrics, otlp]
      processors: [batch]
      ***REMOVED*** [datadog]
    traces:
      receivers: [otlp]
      processors: [batch]
      ***REMOVED*** [datadog]
    logs:
      receivers: [otlp, filelog]
      processors: [batch]
      ***REMOVED*** [datadog]