# The Licensed Work is (c) 2022 Sygma
# SPDX-License-Identifier: BUSL-1.1

name: OpenTelemetry

on:
  pull_request:
    types: [opened]
    
  push:
    branches:
      - main
    paths-ignore:
      - '!Dockerfile'
      - '!.github/workflows'
      - '!**.yaml'

env:
  AWS_REGION: '${{ secrets.AWS_REGION }}'
  ENVIRONMENT: STAGE
  AWS_STAGE: '${{ secrets.AWS_ARN }}'
  REGISTRY: 'ghcr.io'
  TAG: 'latest'

jobs:
  push:
    name: push
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: confirmation to run worklflow
        id: confirm 
        if: ${{ github.event_name == 'pull_request' }}
        run: |
            echo "Do you want to proceed (yes/no)"
            read confirmation
            echo "::set-output name=confirmed::$confirmation"
      - name: Proceed if confirm Yes
        if: ${{ steps.confirm.outputs.confirmed == 'yes' }}
        run: |
          echo "Okay Buddy, got your confirmation, workflow pending"
      - name: checkout the source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: login to ghcr
        id: ghcr
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: build / tag / push docker image into ghcr
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.TAG }}